-- ── Seed file (re-runnable) ───────────────────────────────────────────────
-- Creates the 4 game-data tables if they don't exist, then truncates and
-- re-inserts all seed data on every run.

CREATE TABLE IF NOT EXISTS resources (
  id        SERIAL PRIMARY KEY,
  name      VARCHAR(100) NOT NULL UNIQUE,
  type      VARCHAR(20)  NOT NULL,
  icon      VARCHAR(20),
  info      TEXT,
  available BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS terrains (
  id    SERIAL PRIMARY KEY,
  name  VARCHAR(50) NOT NULL UNIQUE,
  color VARCHAR(20) NOT NULL,
  icon  VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS resource_locations (
  id          SERIAL PRIMARY KEY,
  resource_id INTEGER NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
  terrain     VARCHAR(50)  NOT NULL REFERENCES terrains(name),
  location    VARCHAR(100) NOT NULL,
  stars       SMALLINT NOT NULL DEFAULT 0 CHECK (stars BETWEEN 0 AND 5),
  UNIQUE (resource_id, terrain, location)
);

CREATE TABLE IF NOT EXISTS production_chain (
  id              SERIAL PRIMARY KEY,
  resource_id     INTEGER NOT NULL UNIQUE REFERENCES resources(id) ON DELETE CASCADE,
  processed_name  VARCHAR(100) NOT NULL,
  final1_name     VARCHAR(100),
  final1_category VARCHAR(30),
  final2_name     VARCHAR(100),
  final2_category VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS map_regions (
  id         SERIAL PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  parent     VARCHAR(100) NOT NULL DEFAULT '',
  lat_min    DECIMAL(7,4) NOT NULL,
  lat_max    DECIMAL(7,4) NOT NULL,
  lng_min    DECIMAL(8,4) NOT NULL,
  lng_max    DECIMAL(8,4) NOT NULL,
  center_lat DECIMAL(7,4),
  center_lng DECIMAL(8,4),
  zoom       SMALLINT,
  UNIQUE (name, parent)
);

-- ── Truncate and re-seed ──────────────────────────────────────────────────
TRUNCATE production_chain, resource_locations, terrains, map_regions RESTART IDENTITY CASCADE;
DELETE FROM resources; ALTER SEQUENCE resources_id_seq RESTART WITH 1;

-- ── Terrains ──────────────────────────────────────────────────────────────
INSERT INTO terrains (name, color, icon) VALUES
  ('Flat',     '#72c24a', '🌾'),
  ('Arid',     '#d4980a', '🌵'),
  ('Desert',   '#f0d040', '🏜️'),
  ('Tropical', '#1a7d38', '🌴'),
  ('Wet',      '#2878c0', '💧'),
  ('Cold',     '#a0d4ee', '❄️'),
  ('Hill',     '#3a9e7a', '⛰️'),
  ('Mountain', '#b86820', '🏔️');

-- ── Resources ─────────────────────────────────────────────────────────────
INSERT INTO resources (name, type, icon, info, available) VALUES
  -- Ore (available)
  ('Tin Ore',       'Ore',      '⛏️', 'Used in crafting bronze tools and alloys.',            true),
  ('Copper Ore',    'Ore',      '⛏️', 'Used for early tools, weapons and currency.',           true),
  ('Iron Ore',      'Ore',      '⛏️', 'Essential for crafting iron tools, weapons and armor.', true),
  -- Ore (unavailable)
  ('Alloy Ore',     'Ore',      '⛏️', 'A special ore not found in local settlements.',         false),
  -- Stone (available)
  ('Clay',          'Stone',    '🏺', 'Used for pottery, bricks and construction.',            true),
  ('Sandstone',     'Stone',    '🪨', 'A sedimentary rock used in arid region construction.',  true),
  ('Limestone',     'Stone',    '🪨', 'A common building material and source of lime for mortar.', true),
  ('Granite',       'Stone',    '🪨', 'A hard igneous rock used in high-quality construction.', true),
  -- Stone (unavailable)
  ('FieldStone',    'Stone',    '🪨', 'Rough stone not found in local settlements.',            false),
  -- Wood (available)
  ('White Oak',     'Wood',     '🌳', 'A durable hardwood prized for furniture and shipbuilding.', true),
  ('Rosewood',      'Wood',     '🌲', 'A fine fragrant hardwood used in luxury goods.',         true),
  ('Palm Tree',     'Wood',     '🌴', 'Provides timber, fiber and food products.',              true),
  ('Mahogany',      'Wood',     '🌲', 'A prized tropical hardwood used in fine furniture.',     true),
  ('Maple',         'Wood',     '🍁', 'A hardwood also used for syrup and charcoal production.', true),
  ('Red Oak',       'Wood',     '🌲', 'A strong hardwood used in construction and barrels.',    true),
  ('Chestnut Wood', 'Wood',     '🌰', 'Rot-resistant wood used for furniture and fencing.',     true),
  ('Pine',          'Wood',     '🌲', 'A versatile softwood used for construction and paper.',  true),
  -- Wood (unavailable)
  ('Poplar',        'Wood',     '🌲', 'A fast-growing wood not found in local settlements.',    false),
  -- Raw Food (available)
  ('Milk',          'Raw Food', '🥛', 'Produced by grazing cattle. Used in cheese and butter.', true),
  ('Rye',           'Raw Food', '🌾', 'A hardy grain used for bread and whiskey.',              true),
  ('Maize',         'Raw Food', '🌽', 'A versatile crop used for flour, oil and animal feed.',  true),
  ('Chickpeas',     'Raw Food', '🫘', 'A protein-rich legume grown in dry climates.',           true),
  ('Pig',           'Raw Food', '🐷', 'Provides pork, lard and leather.',                       true),
  ('Chicken',       'Raw Food', '🐔', 'Provides meat, eggs and feathers.',                      true),
  ('Rice',          'Raw Food', '🌾', 'A staple grain requiring wet conditions.',                true),
  ('Trout',         'Raw Food', '🐟', 'A prized freshwater fish.',                              true),
  ('Barley',        'Raw Food', '🌾', 'A grain used for bread, beer and animal feed.',          true),
  ('Salmon',        'Raw Food', '🐟', 'A prized fish from cold, fast-moving waters.',           true),
  ('Grapes',        'Raw Food', '🍇', 'Used for wine, raisins and fresh eating.',               true),
  ('Potatoes',      'Raw Food', '🥔', 'A versatile root vegetable for cold climates.',          true);

-- ── Resource locations ────────────────────────────────────────────────────
INSERT INTO resource_locations (resource_id, terrain, location, stars)
SELECT r.id, v.terrain, v.location, v.stars
FROM (VALUES
  ('Tin Ore','Flat','Plains',0),
  ('Tin Ore','Flat','Moorland',0),
  ('Tin Ore','Flat','Scrubland',0),
  ('Tin Ore','Flat','Swamp',0),
  ('Tin Ore','Desert','Desert',0),
  ('Tin Ore','Desert','Salt Flats',0),
  ('Tin Ore','Desert','Plateau',0),
  ('Tin Ore','Desert','Savannah',0),
  ('Tin Ore','Desert','Dunes',0),
  ('Tin Ore','Desert','Scrubland',0),
  ('Tin Ore','Desert','Steppe',0),
  ('Tin Ore','Wet','Delta',0),
  ('Tin Ore','Wet','Tundra',0),
  ('Tin Ore','Wet','Lake',0),
  ('Tin Ore','Wet','Moorland',0),
  ('Tin Ore','Wet','Bushes',0),
  ('Tin Ore','Wet','Swamp',0),
  ('Copper Ore','Arid','Prairie',0),
  ('Copper Ore','Arid','Savannah',0),
  ('Copper Ore','Arid','Steppe',0),
  ('Copper Ore','Arid','Dunes',0),
  ('Copper Ore','Arid','Salt Flats',0),
  ('Copper Ore','Arid','Canyon',0),
  ('Copper Ore','Arid','Rocks',0),
  ('Copper Ore','Mountain','Caves',0),
  ('Copper Ore','Mountain','Peaks',0),
  ('Copper Ore','Mountain','Rocks',0),
  ('Copper Ore','Mountain','Canyon',0),
  ('Copper Ore','Mountain','Extinct volcano',0),
  ('Copper Ore','Mountain','Waterfall',0),
  ('Copper Ore','Mountain','Mountain',0),
  ('Copper Ore','Mountain','Plateau',0),
  ('Iron Ore','Tropical','Extinct volcano',0),
  ('Iron Ore','Tropical','Bushes',0),
  ('Iron Ore','Tropical','Lake',0),
  ('Iron Ore','Cold','Arctic Tundra',0),
  ('Iron Ore','Cold','Glacier',0),
  ('Iron Ore','Cold','Mountain',0),
  ('Iron Ore','Cold','Tundra',0),
  ('Iron Ore','Hill','Hills',0),
  ('Iron Ore','Hill','Rocky Plains',0),
  ('Iron Ore','Hill','Forested Hills',0),
  ('Iron Ore','Hill','River',0),
  ('Iron Ore','Hill','Waterfall',0),
  ('Clay','Flat','Plains',0),
  ('Clay','Flat','Floodplains',0),
  ('Clay','Flat','Moorland',0),
  ('Clay','Flat','Swamp',0),
  ('Clay','Wet','Wetland',0),
  ('Clay','Wet','Marsh',0),
  ('Clay','Wet','Tundra',0),
  ('Clay','Wet','Lake',0),
  ('Clay','Wet','Moorland',0),
  ('Clay','Wet','Swamp',0),
  ('Sandstone','Arid','Prairie',0),
  ('Sandstone','Arid','Volcano',0),
  ('Sandstone','Arid','Savannah',0),
  ('Sandstone','Arid','Dunes',0),
  ('Sandstone','Arid','Salt Flats',0),
  ('Sandstone','Arid','Canyon',0),
  ('Sandstone','Arid','Rocks',0),
  ('Sandstone','Desert','Desert',0),
  ('Sandstone','Desert','Salt Flats',0),
  ('Sandstone','Desert','Plateau',0),
  ('Sandstone','Desert','Savannah',0),
  ('Sandstone','Desert','Dunes',0),
  ('Limestone','Tropical','Extinct volcano',0),
  ('Limestone','Tropical','Forested Hills',0),
  ('Limestone','Tropical','Lake',0),
  ('Limestone','Cold','Arctic Tundra',0),
  ('Limestone','Cold','Glacier',0),
  ('Limestone','Cold','Mountain',0),
  ('Limestone','Cold','Marsh',0),
  ('Limestone','Cold','Tundra',0),
  ('Limestone','Cold','River',0),
  ('Granite','Hill','Hills',0),
  ('Granite','Hill','Rocky Plains',0),
  ('Granite','Hill','Forested Hills',0),
  ('Granite','Hill','River',0),
  ('Granite','Hill','Waterfall',0),
  ('Granite','Mountain','Caves',0),
  ('Granite','Mountain','Peaks',0),
  ('Granite','Mountain','Rocks',0),
  ('Granite','Mountain','Canyon',0),
  ('Granite','Mountain','Extinct volcano',0),
  ('Granite','Mountain','Waterfall',0),
  ('Granite','Mountain','Mountain',0),
  ('Granite','Mountain','Plateau',0),
  ('White Oak','Flat','Woods',0),
  ('White Oak','Flat','Moorland',0),
  ('White Oak','Flat','River',0),
  ('White Oak','Flat','Forest',0),
  ('White Oak','Flat','Scrubland',0),
  ('White Oak','Flat','Swamp',0),
  ('Rosewood','Arid','Prairie',0),
  ('Rosewood','Arid','Volcano',0),
  ('Rosewood','Arid','Savannah',0),
  ('Palm Tree','Desert','Oasis',0),
  ('Palm Tree','Desert','Savannah',0),
  ('Palm Tree','Desert','Scrubland',0),
  ('Mahogany','Tropical','Rainforest',0),
  ('Mahogany','Tropical','Jungle',0),
  ('Mahogany','Tropical','Forested Hills',0),
  ('Mahogany','Tropical','River',0),
  ('Mahogany','Tropical','Forest',0),
  ('Mahogany','Tropical','Bushes',0),
  ('Maple','Wet','Lake',0),
  ('Maple','Wet','Moorland',0),
  ('Maple','Wet','Bushes',0),
  ('Maple','Wet','Swamp',0),
  ('Red Oak','Cold','Dark Forest',0),
  ('Red Oak','Cold','Mountain',0),
  ('Red Oak','Cold','Taiga',0),
  ('Chestnut Wood','Hill','Dark Forest',0),
  ('Chestnut Wood','Hill','Forested Hills',0),
  ('Chestnut Wood','Hill','Woods',0),
  ('Chestnut Wood','Hill','Waterfall',0),
  ('Chestnut Wood','Hill','Taiga',0),
  ('Pine','Mountain','Extinct volcano',0),
  ('Pine','Mountain','Waterfall',0),
  ('Pine','Mountain','Mountain',0),
  ('Milk','Flat','Plains',0),
  ('Milk','Flat','Woods',0),
  ('Milk','Flat','Moorland',0),
  ('Milk','Flat','Forest',0),
  ('Rye','Flat','Floodplains',0),
  ('Rye','Flat','River',0),
  ('Rye','Arid','Prairie',0),
  ('Rye','Arid','Steppe',0),
  ('Maize','Arid','Volcano',0),
  ('Maize','Arid','Savannah',0),
  ('Chickpeas','Desert','Oasis',0),
  ('Pig','Desert','Plateau',0),
  ('Pig','Desert','Savannah',0),
  ('Pig','Desert','Steppe',0),
  ('Pig','Tropical','Jungle',0),
  ('Pig','Tropical','Extinct volcano',0),
  ('Pig','Tropical','Forested Hills',0),
  ('Pig','Tropical','River',0),
  ('Pig','Tropical','Lake',0),
  ('Chicken','Tropical','Rainforest',0),
  ('Chicken','Tropical','Forest',0),
  ('Chicken','Tropical','Bushes',0),
  ('Rice','Wet','Wetland',0),
  ('Rice','Wet','Marsh',0),
  ('Rice','Wet','Tundra',0),
  ('Rice','Wet','Moorland',0),
  ('Trout','Wet','Delta',0),
  ('Trout','Wet','Lake',0),
  ('Trout','Hill','River',0),
  ('Trout','Hill','Waterfall',0),
  ('Barley','Cold','Arctic Tundra',0),
  ('Barley','Cold','Dark Forest',0),
  ('Barley','Cold','Tundra',0),
  ('Barley','Cold','Taiga',0),
  ('Salmon','Cold','Marsh',0),
  ('Salmon','Cold','River',0),
  ('Salmon','Mountain','Waterfall',0),
  ('Grapes','Hill','Hills',0),
  ('Grapes','Hill','Rocky Plains',0),
  ('Grapes','Hill','Dark Forest',0),
  ('Grapes','Hill','Forested Hills',0),
  ('Grapes','Hill','Woods',0),
  ('Grapes','Hill','Taiga',0),
  ('Potatoes','Mountain','Extinct volcano',0),
  ('Potatoes','Mountain','Mountain',0),
  ('Potatoes','Mountain','Plateau',0)
) AS v(res_name, terrain, location, stars)
JOIN resources r ON r.name = v.res_name;

-- ── Production chains ─────────────────────────────────────────────────────
INSERT INTO production_chain (resource_id, processed_name, final1_name, final1_category, final2_name, final2_category)
SELECT r.id, v.proc, v.f1, v.c1, v.f2, v.c2
FROM (VALUES
  ('Rye',           'Rye Bread',         'Rye Beer',        'Luxury', NULL,           NULL),
  ('Salmon',        'Salmon Filet',       'Smoked Salmon',   'Luxury', NULL,           NULL),
  ('Chicken',       'Chicken Meat',       'Smoked Chicken',  'Luxury', NULL,           NULL),
  ('Rice',          'White Rice',         'Sake',            'Luxury', NULL,           NULL),
  ('Pig',           'Pork',               'Sausage',         'Luxury', NULL,           NULL),
  ('Grapes',        'Grape Juice',        'Wine',            'Luxury', NULL,           NULL),
  ('Trout',         'Trout Filet',        'Smoked Trout',    'Luxury', NULL,           NULL),
  ('Barley',        'Malt',               'Whiskey',         'Luxury', NULL,           NULL),
  ('Milk',          'Butter',             'Cheese',          'Luxury', NULL,           NULL),
  ('Potatoes',      'Fries',              'Wodka',           'Luxury', NULL,           NULL),
  ('Maize',         'Maize Flour',        'Tortillas',       'Luxury', NULL,           NULL),
  ('Chickpeas',     'Chickpea Flour',     'Hummus',          'Luxury', NULL,           NULL),
  ('Clay',          'Clay Bricks',        'Monument',        'Relic',  'Pot',          'Ware'),
  ('Granite',       'Granite Blocks',     'Column',          'Relic',  'Mortar',       'Ware'),
  ('Limestone',     'Limestone Blocks',   'Arch',            'Relic',  'Jar',          'Ware'),
  ('Sandstone',     'Sandstone Blocks',   'Vase',            'Relic',  'Glass Bowl',   'Ware'),
  ('FieldStone',    'Fieldstone Blocks',  NULL,              NULL,     NULL,           NULL),
  ('Iron Ore',      'Iron',               'Ironwork',        'Relic',  'Sword',        'Weapon'),
  ('Copper Ore',    'Copper',             'Statue',          'Relic',  'Helmet',       'Armor'),
  ('Tin Ore',       'Tin',                'Chandelier',      'Relic',  'Chainmail',    'Armor'),
  ('Alloy Ore',     'Alloy',              NULL,              NULL,     NULL,           NULL),
  ('White Oak',     'White Oak Planks',   'Logbow',          'Weapon', 'Table',        'Ware'),
  ('Chestnut Wood', 'Chestnut Planks',    'Crossbow',        'Weapon', 'Chest',        'Ware'),
  ('Palm Tree',     'Flywood',            'Spear',           'Weapon', 'Bookcase',     'Ware'),
  ('Red Oak',       'Red Oak Planks',     'Catapult',        'Weapon', 'Chair',        'Ware'),
  ('Rosewood',      'Rosewood Planks',    'Longbow',         'Weapon', 'Hatstand',     'Ware'),
  ('Maple',         'Maple Planks',       'Crossbow',        'Weapon', 'Stool',        'Ware'),
  ('Mahogany',      'Mahogany Planks',    'Catapult',        'Weapon', 'Bench',        'Ware'),
  ('Pine',          'Deal Timber',        'Spear',           'Weapon', 'Desk',         'Ware'),
  ('Poplar',        'Poplar Planks',      NULL,              NULL,     NULL,           NULL)
) AS v(res_name, proc, f1, c1, f2, c2)
JOIN resources r ON r.name = v.res_name;

-- ── Map regions ───────────────────────────────────────────────────────────
INSERT INTO map_regions (name, parent, lat_min, lat_max, lng_min, lng_max, center_lat, center_lng, zoom) VALUES
  ('Netherlands',    '',             50.7, 53.6,   3.3,   7.3, 52.3,   5.3, 8),
  ('Belgium',        '',             49.5, 51.5,   2.5,   6.4, 50.6,   4.5, 8),
  ('Luxembourg',     '',             49.4, 50.2,   5.7,   6.5, 49.8,   6.1, 9),
  ('Germany',        '',             47.3, 55.1,   5.9,  15.1, 51.2,  10.5, 6),
  ('France',         '',             41.3, 51.1,  -5.1,   9.6, 46.5,   2.3, 6),
  ('United Kingdom', '',             49.9, 60.9,  -8.2,   1.8, 54.5,  -3.5, 6),
  ('Ireland',        '',             51.4, 55.4, -10.5,  -5.9, 53.2,  -8.2, 7),
  ('Spain',          '',             35.9, 43.8,  -9.3,   4.3, 40.4,  -3.7, 6),
  ('Portugal',       '',             36.9, 42.2,  -9.5,  -6.2, 39.6,  -8.0, 7),
  ('Italy',          '',             35.5, 47.1,   6.6,  18.5, 42.5,  12.5, 6),
  ('Switzerland',    '',             45.8, 47.8,   5.9,  10.5, 46.8,   8.2, 8),
  ('Austria',        '',             46.4, 49.0,   9.5,  17.2, 47.7,  13.3, 7),
  ('Denmark',        '',             54.6, 57.8,   8.1,  15.2, 56.2,  11.7, 7),
  ('Sweden',         '',             55.3, 69.1,  11.0,  24.2, 62.2,  17.6, 5),
  ('Norway',         '',             57.9, 71.2,   4.5,  31.2, 64.6,  17.9, 5),
  ('Finland',        '',             59.8, 70.1,  20.0,  31.6, 64.5,  26.0, 5),
  ('Poland',         '',             49.0, 54.9,  14.1,  24.2, 52.0,  19.1, 6),
  ('Czech Republic', '',             48.6, 51.1,  12.1,  18.9, 49.8,  15.5, 7),
  ('United States',  '',             24.5, 49.4,-124.8, -66.9, 39.5, -98.5, 5),
  ('Alabama',        'United States', 30.2, 35.0, -88.5, -84.9, NULL, NULL, NULL),
  ('Alaska',         'United States', 54.6, 71.4,-168.0,-129.9, NULL, NULL, NULL),
  ('Arizona',        'United States', 31.3, 37.0,-114.8,-109.0, NULL, NULL, NULL),
  ('Arkansas',       'United States', 33.0, 36.5, -94.6, -89.6, NULL, NULL, NULL),
  ('California',     'United States', 32.5, 42.0,-124.5,-114.1, NULL, NULL, NULL),
  ('Colorado',       'United States', 37.0, 41.0,-109.1,-102.0, NULL, NULL, NULL),
  ('Connecticut',    'United States', 41.0, 42.1, -73.7, -71.8, NULL, NULL, NULL),
  ('Delaware',       'United States', 38.5, 39.8, -75.8, -75.0, NULL, NULL, NULL),
  ('Florida',        'United States', 24.5, 31.0, -87.6, -80.0, NULL, NULL, NULL),
  ('Georgia',        'United States', 30.4, 35.0, -85.6, -80.8, NULL, NULL, NULL),
  ('Hawaii',         'United States', 18.9, 22.2,-160.3,-154.8, NULL, NULL, NULL),
  ('Idaho',          'United States', 42.0, 49.0,-117.2,-111.0, NULL, NULL, NULL),
  ('Illinois',       'United States', 37.0, 42.5, -91.5, -87.5, NULL, NULL, NULL),
  ('Indiana',        'United States', 37.8, 41.8, -88.1, -84.8, NULL, NULL, NULL),
  ('Iowa',           'United States', 40.4, 43.5, -96.6, -90.1, NULL, NULL, NULL),
  ('Kansas',         'United States', 37.0, 40.0,-102.1, -94.6, NULL, NULL, NULL),
  ('Kentucky',       'United States', 36.5, 39.1, -89.6, -81.9, NULL, NULL, NULL),
  ('Louisiana',      'United States', 29.0, 33.0, -94.1, -89.0, NULL, NULL, NULL),
  ('Maine',          'United States', 43.1, 47.5, -71.1, -66.9, NULL, NULL, NULL),
  ('Maryland',       'United States', 37.9, 39.7, -79.5, -75.1, NULL, NULL, NULL),
  ('Massachusetts',  'United States', 41.2, 42.9, -73.5, -69.9, NULL, NULL, NULL),
  ('Michigan',       'United States', 41.7, 48.3, -90.4, -82.4, NULL, NULL, NULL),
  ('Minnesota',      'United States', 43.5, 49.4, -97.2, -89.5, NULL, NULL, NULL),
  ('Mississippi',    'United States', 30.2, 35.0, -91.7, -88.1, NULL, NULL, NULL),
  ('Missouri',       'United States', 36.0, 40.6, -95.8, -89.1, NULL, NULL, NULL),
  ('Montana',        'United States', 44.4, 49.0,-116.1,-104.0, NULL, NULL, NULL),
  ('Nebraska',       'United States', 40.0, 43.0,-104.1, -95.3, NULL, NULL, NULL),
  ('Nevada',         'United States', 35.0, 42.0,-120.0,-114.0, NULL, NULL, NULL),
  ('New Hampshire',  'United States', 42.7, 45.3, -72.6, -70.7, NULL, NULL, NULL),
  ('New Jersey',     'United States', 38.9, 41.4, -75.6, -73.9, NULL, NULL, NULL),
  ('New Mexico',     'United States', 31.3, 37.0,-109.1,-103.0, NULL, NULL, NULL),
  ('New York',       'United States', 40.5, 45.0, -79.8, -71.9, NULL, NULL, NULL),
  ('North Carolina', 'United States', 33.8, 36.6, -84.3, -75.5, NULL, NULL, NULL),
  ('North Dakota',   'United States', 45.9, 49.0,-104.1, -96.6, NULL, NULL, NULL),
  ('Ohio',           'United States', 38.4, 42.3, -84.8, -80.5, NULL, NULL, NULL),
  ('Oklahoma',       'United States', 33.6, 37.0,-103.0, -94.4, NULL, NULL, NULL),
  ('Oregon',         'United States', 42.0, 46.3,-124.6,-116.5, NULL, NULL, NULL),
  ('Pennsylvania',   'United States', 39.7, 42.3, -80.5, -74.7, NULL, NULL, NULL),
  ('Rhode Island',   'United States', 41.1, 42.0, -71.9, -71.1, NULL, NULL, NULL),
  ('South Carolina', 'United States', 32.0, 35.2, -83.4, -78.5, NULL, NULL, NULL),
  ('South Dakota',   'United States', 42.5, 45.9,-104.1, -96.4, NULL, NULL, NULL),
  ('Tennessee',      'United States', 35.0, 36.7, -90.3, -81.6, NULL, NULL, NULL),
  ('Texas',          'United States', 25.8, 36.5,-106.7, -93.5, NULL, NULL, NULL),
  ('Utah',           'United States', 37.0, 42.0,-114.1,-109.0, NULL, NULL, NULL),
  ('Vermont',        'United States', 42.7, 45.0, -73.4, -71.5, NULL, NULL, NULL),
  ('Virginia',       'United States', 36.5, 39.5, -83.7, -75.2, NULL, NULL, NULL),
  ('Washington',     'United States', 45.5, 49.0,-124.8,-116.9, NULL, NULL, NULL),
  ('West Virginia',  'United States', 37.2, 40.6, -82.6, -77.7, NULL, NULL, NULL),
  ('Wisconsin',      'United States', 42.5, 47.1, -92.9, -86.8, NULL, NULL, NULL),
  ('Wyoming',        'United States', 41.0, 45.0,-111.1,-104.1, NULL, NULL, NULL);
